---
title: "cjsOutput"
output: html_document
---
```{r load and wrangle}
out<-readRDS("results/cjsMcmc.rds")
library(reshape2)
library(data.table)
library(dplyr)
library(plotHacks)
library(coda)

outArray<-as.array.mcmc.list(out)

wrangle<-function(x,margin=c(2)){
  getSummary<-function(x){
    meanX<-mean(x)
    quantiles<-quantile(x,c(0.025,0.975))
    return(c(meanX,quantiles))
  }
  stringSplit<-function(x,split,element){
    sapply(strsplit(x,split), "[[", element)
  }
  
  result<-apply(x,MARGIN=margin,FUN=getSummary) %>%
          melt() %>%
          dcast(var~Var1) %>%
          data.table()
    
  setnames(result,c("var","mean","lower","upper"))
  result[,var:=as.character(var)]
  
  result[,parameter:=unlist(strsplit(var,"[[]"))[seq(1,nrow(result)*2-1,2)]]
  getIndices<-function(x){
    ch<-strsplit(x[1],"")[[1]]
    n<-sum(ch==",")+1
    return(n)
  }
  nIndices<-list()
  for(p in unique(result$parameter)){
    nIndices[[p]]<-getIndices(result[parameter==p,var])

      groupedIndices<-result[parameter==p,var] %>%
        stringSplit("[[]",2) %>% 
        stringSplit("[]]",1)
    for(w in 1:nIndices[[p]]){
      result[parameter==p,paste0("i",w):=.(stringSplit(groupedIndices,",",w))]
    }
  }
  nIndices<<-nIndices
  return(result)
}

results<-wrangle(outArray)
# alive<-results[parameter=="alive",
#                c("mean","lower","upper",paste0("i",1:nIndices[['alive']])),
#                with=F] %>%
#        setnames(c("i1","i2","i3","i4"),c("season","year","river","stage"))
phiBeta<-results[parameter=="phiBeta",
               c("mean","lower","upper",paste0("i",1:nIndices[['phiBeta']])),
               with=F] %>%
      setnames(c("i1","i2","i3","i4"),c("season","year","river","stage"))
pBeta<-results[parameter=="pBeta",
               c("mean","lower","upper",paste0("i",1:nIndices[['pBeta']])),
               with=F] %>%
      setnames(c("i1","i2"),c("river","beta"))
```

```{r plot p by flow}
xLength<-seq(-2,2,0.01)
xFlow<-seq(-2,2,0.01)
#   tiff.par(paste0("results/p",".tif"),
#            mfrow=c(2,2))
logitP<-p<-array(NA,dim=c(length(xFlow),3))
  for(r in 1:4){
    plot(NA,xlim=c(min(xLength),max(xLength)),ylim=c(0,1))
      b1<-t(pBeta[beta==1&river==r,.(mean,lower,upper)] )[,1]
      b2<-t(pBeta[beta==2&river==r,.(mean,lower,upper)] )[,1]
      b3<-t(pBeta[beta==3&river==r,.(mean,lower,upper)] )[,1]
      for(d in 1:3){
        logitP[,d]<-b1[d]+b2[d]*xLength
        p[,d]<-1/(1+exp(-logitP[,d]))
        points(p[,d]~xLength,type='l',col=palette()[r],lty=as.numeric(d>1)+1)
      }
  }

  for(r in 1:4){
    plot(NA,xlim=c(min(xLength),max(xLength)),ylim=c(0,1))
      b1<-t(pBeta[beta==1&river==r,.(mean,lower,upper)] )[,1]
      b2<-t(pBeta[beta==2&river==r,.(mean,lower,upper)] )[,1]
      b3<-t(pBeta[beta==3&river==r,.(mean,lower,upper)] )[,1]
      for(d in 1:3){
        logitP[,d]<-b1[d]+b3[d]*xFlow
        p[,d]<-1/(1+exp(-logitP[,d]))
        points(p[,d]~xFlow,type='l',col=palette()[r],lty=as.numeric(d>1)+1)
      }
  }

saveRDS(pBeta,"results/pForYoy.rds")
  # dev.off()

```

```{r traceplots}
#traceplot(out)
```